default: &default
  adapter: postgresql
  encoding: utf-8
  host: <%= ENV.fetch("DATABASE_HOST", "database") %> 
  username: <%= ENV.fetch("POSTGRES_USER", "postgres" ) %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", '') %>
  port: <%= ENV.fetch('POSTGRES_PORT', '') %>
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= Sidekiq.server? ? ENV.fetch('SIDEKIQ_CONCURRENCY', 10):ENV.fetch('RAILS_MAX_THREADS', 5) %>  


development:
  <<: *default
  database: search_box_development



test:
  <<: *default
  database: search_box_test



production:
  <<: *default
  database: search_box_production
